import { expect, test } from '@playwright/test';
import type { useRackStore } from '../../src/store/rackStore';
import { abFixture } from '../fixtures/abCableFixture';
const state = () => (window as unknown as { __rackStore: typeof useRackStore }).__rackStore.getState();
for (const width of [1280, 390]) test(`A–B preview, atomic confirm, cancel and persistence at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: width === 1280 ? 850 : 844 });
  await page.goto('/');
  await page.evaluate(layout => (window as unknown as { __rackStore: typeof useRackStore }).__rackStore.getState().loadLayout(layout), abFixture());
  await page.getByRole('button', { name: 'Cable', exact: true }).click();
  if (width < 1024) await page.getByRole('button', { name: 'Cable list', exact: true }).click();
  await page.getByRole('button', { name: 'Connect A–B · 經配線架', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Connect A–B · 經配線架接線', exact: true });
  await expect(dialog).toBeVisible();
  await dialog.getByLabel('Device B', { exact: true }).selectOption('Switch B');
  await dialog.getByLabel('Path preference', { exact: true }).selectOption('two-panels');
  await dialog.getByRole('button', { name: 'Preview paths · 預覽路徑', exact: true }).click();
  await expect(dialog.getByText('Keep P1#3–P2#7', { exact: false })).toBeVisible();
  await expect(dialog.getByText('Internal jack hop · 內部連通 — no cable / BOM', { exact: true })).toHaveCount(2);
  await dialog.evaluate(el => { el.scrollTop = 0; });
  await page.screenshot({ path: `../ab-selection-${width}.png` });
  const confirm = dialog.getByRole('button', { name: 'Confirm 2 new segment(s) · 確認', exact: true });
  await confirm.scrollIntoViewIfNeeded(); await expect(confirm).toBeInViewport();
  await dialog.evaluate(el => { el.scrollTop = el.scrollHeight; });
  await page.screenshot({ path: `../ab-preview-${width}.png` });
  await confirm.click(); await expect(dialog.getByRole('button', { name: 'Connection present · 已完成', exact: true })).toBeDisabled();
  await expect.poll(() => page.evaluate(state).then(s => s.layout.cables.length)).toBe(3);
  await page.evaluate(() => (window as unknown as { __rackStore: typeof useRackStore }).__rackStore.getState().undo());
  await expect.poll(() => page.evaluate(state).then(s => s.layout.cables.length)).toBe(1);
  await expect(confirm).toBeEnabled();
  await page.evaluate(() => (window as unknown as { __rackStore: typeof useRackStore }).__rackStore.getState().redo());
  await page.keyboard.press('Escape'); await expect(dialog).toHaveCount(0);
  await page.reload(); await page.getByRole('button', { name: 'Cable', exact: true }).click();
  if (width < 1024) await page.getByRole('button', { name: 'Cable list', exact: true }).click();
  await page.getByRole('button', { name: 'Connect A–B · 經配線架', exact: true }).click();
  await dialog.getByLabel('Device B', { exact: true }).selectOption('Switch B');
  await dialog.getByLabel('Path preference', { exact: true }).selectOption('two-panels');
  await dialog.getByRole('button', { name: 'Preview paths · 預覽路徑', exact: true }).click();
  await expect(dialog.getByRole('button', { name: 'Already connected · 確認已有接線', exact: true })).toBeVisible();
  await dialog.getByRole('button', { name: 'Cancel · 取消', exact: true }).focus(); await page.keyboard.press('Shift+Tab');
  expect(await dialog.evaluate(el => el.contains(document.activeElement))).toBeTruthy();
  await page.keyboard.press('Escape'); await expect(dialog).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
});

test('tidy preserves cable identity, warns about manual routes, and supports undo/redo in both views', async ({ page }) => {
  await page.goto('/'); const fixture = abFixture();
  fixture.cables[0].routingOrigin = 'panel-tidy'; fixture.cables[0].manualPath = [{ kind: 'manager', deviceId: 'missing', side: 'left' }];
  await page.evaluate(layout => (window as unknown as { __rackStore: typeof useRackStore }).__rackStore.getState().loadLayout(layout), fixture);
  await page.getByRole('button', { name: 'Cable', exact: true }).click();
  await page.getByRole('button', { name: '整理走線 · Tidy routes', exact: true }).click();
  await expect(page.getByTestId('device-library-panel').getByText('Tidied 1 panel cable route(s). One Undo restores them.', { exact: false })).toBeVisible();
  const after = await page.evaluate(state).then(s => s.layout.cables[0]);
  expect(after.id).toBe('installed-trunk'); expect(after.fromPort?.index).toBe(2); expect(after.toPort?.index).toBe(6); expect(after.lengthMm).toBe(3000);
  await page.screenshot({ path: '../panel-tidy.png', fullPage: true });
  await page.getByRole('button', { name: '整理走線 · Tidy routes', exact: true }).click();
  await expect(page.getByTestId('device-library-panel').getByText('No routing improvement found.', { exact: false })).toBeVisible();
  await page.evaluate(() => (window as unknown as { __rackStore: typeof useRackStore }).__rackStore.getState().undo());
  expect(await page.evaluate(state).then(s => s.layout.cables[0].manualPath)).toEqual(fixture.cables[0].manualPath);
  await page.evaluate(() => (window as unknown as { __rackStore: typeof useRackStore }).__rackStore.getState().redo());
  await page.getByRole('button', { name: '3D routing', exact: true }).click();
  const viewer = page.getByTestId('cable-viewer-3d');
  await expect(viewer.locator('canvas')).toBeVisible();
  await viewer.getByLabel('Camera view').selectOption('rear-angle');
  await page.waitForTimeout(1200);
  await expect(page.locator('#runtime-error-overlay')).toHaveCount(0);
  await page.screenshot({ path: '../panel-tidy-3d.png', fullPage: true });
  expect(await page.evaluate(state).then(s => s.layout.cables[0])).toEqual(after);
});

test('changing a candidate clears the preview; stale previews reject atomically', async ({ page }) => {
  await page.goto('/'); await page.evaluate(layout => (window as unknown as { __rackStore: typeof useRackStore }).__rackStore.getState().loadLayout(layout), abFixture());
  await page.getByRole('button', { name: 'Cable', exact: true }).click();
  await page.getByRole('button', { name: 'Connect A–B · 經配線架', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Connect A–B · 經配線架接線', exact: true });
  await dialog.getByLabel('Device B', { exact: true }).selectOption('Switch B');
  await dialog.getByRole('button', { name: 'Preview paths · 預覽路徑', exact: true }).click();
  await expect(dialog.getByRole('list', { name: 'Physical path preview' })).toBeVisible();
  await dialog.getByLabel('Socket B', { exact: true }).selectOption('1');
  await expect(dialog.getByRole('list', { name: 'Physical path preview' })).toHaveCount(0);
  await dialog.getByRole('button', { name: 'Preview paths · 預覽路徑', exact: true }).click();
  await page.evaluate(() => (window as unknown as { __rackStore: typeof useRackStore }).__rackStore.getState().updateDevice('Switch A', { positionU: 2 }));
  await expect(dialog.getByRole('alert')).toContainText('Layout changed');
  await expect(dialog.getByRole('button', { name: /Confirm .* new segment/ })).toBeDisabled();
  await dialog.getByRole('button', { name: 'Cancel · 取消', exact: true }).click();
  expect(await page.evaluate(state).then(s => s.layout.cables.length)).toBe(1);
  await expect(page.getByRole('button', { name: 'Connect A–B · 經配線架', exact: true })).toBeFocused();
});
