import { expect, test } from '@playwright/test';
import type { useRackStore } from '../../src/store/rackStore';
for (const width of [1440, 1024, 768, 390]) test(`create, find, place, configure and portable backup at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  const menu = page.getByTestId('more-dropdown');
  await menu.locator('summary').click();
  await menu.getByRole('button', { name: 'New rack layout', exact: true }).click();
  await page.getByRole('dialog', { name: 'Start a new layout?', exact: true }).getByRole('button', { name: 'Confirm', exact: true }).click();
  await page.getByRole('textbox', { name: 'Layout name', exact: true }).fill('Portable studio plan');
  if (!(await page.getByTestId('device-library-panel').isVisible())) await page.getByTestId('toggle-device-library').click();
  await page.getByPlaceholder('Search devices').fill('patch');
  await page.getByRole('button', { name: /^Add .* to front$/ }).first().click();
  if (width < 1024 && await page.getByRole('dialog', { name: 'Device library', exact: true }).isVisible()) await page.keyboard.press('Escape');
  if (width < 1280 && !(await page.getByRole('dialog', { name: 'Inspector', exact: true }).isVisible())) await page.getByRole('button', { name: 'Open inspector', exact: true }).click();
  await page.getByRole('textbox', { name: 'Name', exact: true }).fill('Configured office patch panel');
  if (width < 1280) await page.keyboard.press('Escape');
  await expect(page.getByTestId('browser-save-status')).toHaveText('Saved in this browser');
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export JSON backup', exact: true }).click()]);
  expect(download.suggestedFilename()).toMatch(/portable-studio-plan.*\.json$/);
  const stream = await download.createReadStream(); let bytes = ''; for await (const chunk of stream!) bytes += chunk.toString();
  const backup = JSON.parse(bytes); expect(backup.name).toBe('Portable studio plan'); expect(backup.devices[0].name).toBe('Configured office patch panel');
  await page.reload();
  await expect(page.getByRole('textbox', { name: 'Layout name', exact: true })).toHaveValue('Portable studio plan');
  expect(await page.evaluate(() => (window as unknown as { __rackStore: typeof useRackStore }).__rackStore.getState().layout.devices[0].name)).toBe('Configured office patch panel');
  await page.getByRole('button', { name: 'Check Health', exact: true }).click();
  await expect(page.getByTestId('finding-summary-confirmed')).toHaveText('0 Confirmed issues');
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(width); expect(errors).toEqual([]);
});
test('zoom-equivalent short viewport retains reachable canvas, keyboard focus and backup', async ({ page }) => {
  await page.setViewportSize({ width: 720, height: 450 }); await page.emulateMedia({ reducedMotion: 'reduce' }); await page.goto('/');
  const canvas = page.getByRole('region', { name: 'Rack planning canvas', exact: true });
  expect((await canvas.boundingBox())!.height).toBeGreaterThan(200);
  await canvas.scrollIntoViewIfNeeded(); await expect(canvas).toBeInViewport();
  await page.getByTestId('more-dropdown').locator('summary').click(); await page.getByRole('button', { name: 'Load sample', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Load sample layout', exact: true })).toBeVisible();
  await page.keyboard.press('Escape'); await expect(page.getByTestId('more-dropdown').locator('summary')).toBeFocused();
  expect(await page.getByTestId('more-dropdown').locator('summary').evaluate(element => getComputedStyle(element).outlineStyle)).not.toBe('none');
  await page.getByRole('button', { name: 'Export JSON backup', exact: true }).scrollIntoViewIfNeeded();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(720);
});
