import type { CableRoute, ChangeRequest, PlacedDevice, ValidationIssue } from '../types/rack';

export interface ChangeRequestSummary {
  totalCount: number;
  pendingCount: number;
  approvedCount: number;
  rejectedCount: number;
  completedCount: number;
}

export function summarizeChangeRequests(requests: ChangeRequest[]): ChangeRequestSummary {
  const pendingCount = requests.filter((r) => r.status === 'pending').length;
  const approvedCount = requests.filter((r) => r.status === 'approved').length;
  const rejectedCount = requests.filter((r) => r.status === 'rejected').length;
  const completedCount = requests.filter((r) => r.status === 'completed').length;

  return {
    totalCount: requests.length,
    pendingCount,
    approvedCount,
    rejectedCount,
    completedCount,
  };
}

export function validateChangeRequests(
  requests: ChangeRequest[],
  devices: PlacedDevice[],
  cables: CableRoute[]
): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  for (const r of requests) {
    // Check affected devices exist
    for (const deviceId of r.affectedDeviceIds ?? []) {
      if (!devices.some((d) => d.id === deviceId)) {
        issues.push({
          id: `cr-missing-device-${r.id}-${deviceId}`,
          severity: 'warning',
          title: 'Change request references missing device',
          detail: `Change request "${r.title}" references device ${deviceId} which no longer exists.`,
          deviceIds: [deviceId],
        });
      }
    }

    // Check affected cables exist
    for (const cableId of r.affectedCableIds ?? []) {
      if (!cables.some((c) => c.id === cableId)) {
        issues.push({
          id: `cr-missing-cable-${r.id}-${cableId}`,
          severity: 'warning',
          title: 'Change request references missing cable',
          detail: `Change request "${r.title}" references cable ${cableId} which no longer exists.`,
          cableIds: [cableId],
        });
      }
    }

    // Check for high-risk requests without rollback plan
    if (r.riskLevel === 'high' && !r.rollbackPlan?.trim()) {
      issues.push({
        id: `cr-no-rollback-${r.id}`,
        severity: 'warning',
        title: 'High-risk change request lacks rollback plan',
        detail: `Change request "${r.title}" is marked high risk but has no rollback plan.`,
      });
    }
  }

  return issues;
}

export function exportChangeRequestsMarkdown(
  requests: ChangeRequest[],
  devices: PlacedDevice[]
): string {
  const deviceName = (id?: string) => devices.find((d) => d.id === id)?.name ?? id ?? '-';

  const lines: string[] = [
    '# Change Requests',
    '',
    `**Total:** ${requests.length}`,
    '',
    '| Title | Risk | Status | Downtime | Rollback Plan | Affected Devices |',
    '|-------|------|--------|----------|---------------|------------------|',
  ];

  for (const r of requests) {
    const affected = (r.affectedDeviceIds ?? []).map(deviceName).join(', ') || '-';
    lines.push(
      `| ${r.title} | ${r.riskLevel} | ${r.status} | ${r.expectedDowntimeMin ?? '-'} min | ${r.rollbackPlan ?? '-'} | ${affected} |`
    );
  }

  lines.push('', '---', '', '*Generated by Homelab Rack Simulator*', '');
  return lines.join('\n');
}

export function exportChangeRequestsCsv(requests: ChangeRequest[]): string {
  const headers = ['ID', 'Title', 'Description', 'Risk Level', 'Status', 'Expected Downtime (min)', 'Rollback Plan', 'Created At', 'Approved At', 'Approved By', 'Affected Devices', 'Affected Cables'];
  const lines: string[] = [headers.join(',')];

  for (const r of requests) {
    const row = [
      r.id,
      `"${r.title.replace(/"/g, '""')}"`,
      r.description ? `"${r.description.replace(/"/g, '""')}"` : '',
      r.riskLevel,
      r.status,
      r.expectedDowntimeMin?.toString() ?? '',
      r.rollbackPlan ? `"${r.rollbackPlan.replace(/"/g, '""')}"` : '',
      r.createdAt,
      r.approvedAt ?? '',
      r.approvedBy ? `"${r.approvedBy.replace(/"/g, '""')}"` : '',
      (r.affectedDeviceIds ?? []).join('; '),
      (r.affectedCableIds ?? []).join('; '),
    ];
    lines.push(row.join(','));
  }

  return lines.join('\n');
}
