import type { DeviceSensorReading, PlacedDevice } from '../types/rack';

export function summarizeSensorReadings(readings: DeviceSensorReading[]) {
  return {
    total: readings.length,
    withPower: readings.filter((r) => r.powerActualW !== undefined).length,
    withTemp: readings.filter((r) => r.tempActualC !== undefined).length,
    withFan: readings.filter((r) => r.fanActualRpm !== undefined).length,
  };
}

export type SensorAlertSeverity = 'warning' | 'info';

export interface SensorAlert {
  readingId: string;
  deviceId: string;
  deviceName: string;
  type: 'over-power' | 'over-temp' | 'missing-reading';
  severity: SensorAlertSeverity;
  message: string;
}

export function getSensorAlerts(
  readings: DeviceSensorReading[],
  devices: PlacedDevice[]
): SensorAlert[] {
  const deviceMap = new Map(devices.map((d) => [d.id, d]));
  const alerts: SensorAlert[] = [];

  for (const r of readings) {
    const device = deviceMap.get(r.deviceId);
    const deviceName = device?.name ?? r.deviceId;

    if (
      r.powerActualW !== undefined &&
      r.powerPlannedW !== undefined &&
      r.powerActualW > r.powerPlannedW * 1.2
    ) {
      alerts.push({
        readingId: r.id,
        deviceId: r.deviceId,
        deviceName,
        type: 'over-power',
        severity: 'warning',
        message: `Power ${r.powerActualW}W exceeds planned ${r.powerPlannedW}W by >20%`,
      });
    }

    if (
      r.tempActualC !== undefined &&
      r.tempPlannedC !== undefined &&
      r.tempActualC > r.tempPlannedC
    ) {
      alerts.push({
        readingId: r.id,
        deviceId: r.deviceId,
        deviceName,
        type: 'over-temp',
        severity: 'warning',
        message: `Temp ${r.tempActualC}°C exceeds planned ${r.tempPlannedC}°C`,
      });
    }
  }

  const readingDeviceIds = new Set(readings.map((r) => r.deviceId));
  for (const d of devices) {
    if (d.powerW && d.powerW > 0 && !readingDeviceIds.has(d.id)) {
      alerts.push({
        readingId: '',
        deviceId: d.id,
        deviceName: d.name,
        type: 'missing-reading',
        severity: 'info',
        message: 'No sensor reading recorded',
      });
    }
  }

  return alerts;
}

export function exportSensorReadingsMarkdown(
  readings: DeviceSensorReading[],
  devices: PlacedDevice[]
): string {
  const deviceMap = new Map(devices.map((d) => [d.id, d]));
  const summary = summarizeSensorReadings(readings);

  const lines: string[] = [
    '# Device Sensor Readings',
    '',
    `**Total Readings:** ${summary.total}`,
    `**With Power:** ${summary.withPower} · **With Temp:** ${summary.withTemp} · **With Fan:** ${summary.withFan}`,
    '',
  ];

  for (const r of readings) {
    const device = deviceMap.get(r.deviceId);
    lines.push(`## ${device?.name ?? r.deviceId}`, '');
    if (r.recordedAt) lines.push(`**Recorded:** ${r.recordedAt}`);
    if (r.powerActualW !== undefined) {
      const planned = r.powerPlannedW !== undefined ? ` / planned ${r.powerPlannedW}W` : '';
      lines.push(`**Power:** ${r.powerActualW}W${planned}`);
    }
    if (r.tempActualC !== undefined) {
      const planned = r.tempPlannedC !== undefined ? ` / planned ${r.tempPlannedC}°C` : '';
      lines.push(`**Temperature:** ${r.tempActualC}°C${planned}`);
    }
    if (r.fanActualRpm !== undefined) {
      const planned = r.fanPlannedRpm !== undefined ? ` / planned ${r.fanPlannedRpm} RPM` : '';
      lines.push(`**Fan:** ${r.fanActualRpm} RPM${planned}`);
    }
    if (r.notes) lines.push(`**Notes:** ${r.notes}`);
    lines.push('');
  }

  lines.push('---', '', '*Generated by Homelab Rack Simulator*', '');
  return lines.join('\n');
}
