import type { RackEnvironment } from '../types/rack';

export function getEnvironmentStatus(env?: RackEnvironment): {
  tempStatus: 'good' | 'warning' | 'critical';
  humidityStatus: 'good' | 'warning' | 'critical';
  noiseStatus: 'good' | 'warning' | 'critical';
  recommendations: string[];
} {
  const recommendations: string[] = [];

  const temp = env?.roomTempC;
  let tempStatus: 'good' | 'warning' | 'critical' = 'good';
  if (temp !== undefined) {
    if (temp > 32) {
      tempStatus = 'critical';
      recommendations.push('Room temperature is very high. Improve ventilation or add cooling.');
    } else if (temp > 28) {
      tempStatus = 'warning';
      recommendations.push('Room temperature is elevated. Monitor closely.');
    }
  }

  const humidity = env?.roomHumidityPercent;
  let humidityStatus: 'good' | 'warning' | 'critical' = 'good';
  if (humidity !== undefined) {
    if (humidity > 80) {
      humidityStatus = 'critical';
      recommendations.push('Humidity is very high. Risk of condensation and corrosion.');
    } else if (humidity > 65) {
      humidityStatus = 'warning';
      recommendations.push('Humidity is elevated. Consider a dehumidifier.');
    } else if (humidity < 30) {
      humidityStatus = 'warning';
      recommendations.push('Humidity is low. Risk of static discharge.');
    }
  }

  const noise = env?.ambientNoiseDb;
  let noiseStatus: 'good' | 'warning' | 'critical' = 'good';
  if (noise !== undefined) {
    if (noise > 50) {
      noiseStatus = 'critical';
      recommendations.push('Ambient noise is very high. Consider sound dampening or relocating.');
    } else if (noise > 40) {
      noiseStatus = 'warning';
      recommendations.push('Ambient noise is elevated. May affect living spaces.');
    }
  }

  return { tempStatus, humidityStatus, noiseStatus, recommendations };
}

export function exportEnvironmentMarkdown(env?: RackEnvironment): string {
  const lines: string[] = [
    '# Rack Environment Report',
    '',
    env?.recordedAt ? `**Recorded:** ${env.recordedAt}` : '**Recorded:** Not recorded',
    '',
  ];

  if (env?.roomTempC !== undefined) {
    lines.push(`- **Room Temperature:** ${env.roomTempC}°C`);
  }
  if (env?.roomHumidityPercent !== undefined) {
    lines.push(`- **Humidity:** ${env.roomHumidityPercent}%`);
  }
  if (env?.ambientNoiseDb !== undefined) {
    lines.push(`- **Ambient Noise:** ${env.ambientNoiseDb} dB`);
  }
  if (env?.notes) {
    lines.push(`- **Notes:** ${env.notes}`);
  }

  const status = getEnvironmentStatus(env);
  if (status.recommendations.length > 0) {
    lines.push('', '## Recommendations', '');
    for (const r of status.recommendations) {
      lines.push(`- ${r}`);
    }
  }

  lines.push('', '---', '', '*Generated by Homelab Rack Simulator*', '');
  return lines.join('\n');
}
