import type { PlacedDevice } from '../types/rack';

export type FirmwareStatus = 'current' | 'update-available' | 'unknown' | 'not-applicable';

export interface FirmwareSummary {
  trackedCount: number;
  currentCount: number;
  updateAvailableCount: number;
  unknownCount: number;
  notApplicableCount: number;
  outdatedDevices: PlacedDevice[];
}

function normalizeVersion(v: string): string {
  return v
    .toLowerCase()
    .replace(/^v/, '')
    .replace(/[\s_]+/g, '.')
    .replace(/[^0-9a-z.]/g, '');
}

function versionParts(v: string): (number | string)[] {
  return normalizeVersion(v).split('.').map((p) => {
    const n = parseInt(p, 10);
    return Number.isFinite(n) && p === String(n) ? n : p;
  });
}

export function compareVersions(a: string, b: string): number {
  const pa = versionParts(a);
  const pb = versionParts(b);
  const len = Math.max(pa.length, pb.length);
  for (let i = 0; i < len; i++) {
    const va = pa[i] ?? 0;
    const vb = pb[i] ?? 0;
    if (typeof va === 'number' && typeof vb === 'number') {
      if (va !== vb) return va - vb;
    } else {
      const sa = String(va);
      const sb = String(vb);
      if (sa !== sb) return sa.localeCompare(sb);
    }
  }
  return 0;
}

export function getFirmwareStatus(device: PlacedDevice): FirmwareStatus {
  if (device.firmwareVersion === undefined && device.firmwareLatest === undefined) {
    return 'not-applicable';
  }
  if (!device.firmwareVersion || !device.firmwareLatest) {
    return 'unknown';
  }
  const cmp = compareVersions(device.firmwareVersion, device.firmwareLatest);
  if (cmp >= 0) return 'current';
  return 'update-available';
}

export function firmwareStatusLabel(status: FirmwareStatus): string {
  switch (status) {
    case 'current': return 'Current';
    case 'update-available': return 'Update Available';
    case 'unknown': return 'Unknown';
    case 'not-applicable': return 'Not Tracked';
  }
}

export function firmwareStatusColor(status: FirmwareStatus): string {
  switch (status) {
    case 'current': return 'text-emerald-600 dark:text-emerald-400';
    case 'update-available': return 'text-amber-600 dark:text-amber-400';
    case 'unknown': return 'text-slate-600 dark:text-slate-400';
    case 'not-applicable': return 'text-slate-500 dark:text-slate-500';
  }
}

export function firmwareStatusBg(status: FirmwareStatus): string {
  switch (status) {
    case 'current': return 'bg-emerald-500/10 border-emerald-500/30';
    case 'update-available': return 'bg-amber-500/10 border-amber-500/30';
    case 'unknown': return 'bg-slate-500/10 border-slate-500/30';
    case 'not-applicable': return 'bg-slate-500/5 border-slate-500/20';
  }
}

export function summarizeFirmware(devices: PlacedDevice[]): FirmwareSummary {
  const tracked = devices.filter((d) => d.firmwareVersion !== undefined || d.firmwareLatest !== undefined);
  const statuses = tracked.map((d) => getFirmwareStatus(d));
  const currentCount = statuses.filter((s) => s === 'current').length;
  const updateAvailableCount = statuses.filter((s) => s === 'update-available').length;
  const unknownCount = statuses.filter((s) => s === 'unknown').length;
  const notApplicableCount = devices.length - tracked.length;

  const outdatedDevices = tracked
    .filter((d) => getFirmwareStatus(d) === 'update-available')
    .sort((a, b) => compareVersions(a.firmwareVersion ?? '', b.firmwareVersion ?? ''));

  return {
    trackedCount: tracked.length,
    currentCount,
    updateAvailableCount,
    unknownCount,
    notApplicableCount,
    outdatedDevices,
  };
}

export function exportFirmwareMarkdown(devices: PlacedDevice[]): string {
  const lines: string[] = [
    '# Firmware Tracker',
    '',
    `**Total Devices:** ${devices.length}`,
    `**Tracked:** ${devices.filter((d) => d.firmwareVersion !== undefined || d.firmwareLatest !== undefined).length}`,
    '',
    '| Device | Current | Latest | Status | Notes |',
    '|--------|---------|--------|--------|-------|',
  ];

  for (const d of devices) {
    const status = getFirmwareStatus(d);
    if (status === 'not-applicable') continue;
    lines.push(
      `| ${d.name} | ${d.firmwareVersion ?? '-'} | ${d.firmwareLatest ?? '-'} | ${firmwareStatusLabel(status)} | ${d.firmwareNotes ?? ''} |`
    );
  }

  lines.push('', '---', '', '*Generated by Homelab Rack Simulator*', '');
  return lines.join('\n');
}

export function exportFirmwareCsv(devices: PlacedDevice[]): string {
  const headers = ['Device ID', 'Device Name', 'Category', 'Current Version', 'Latest Version', 'Status', 'Notes'];
  const lines: string[] = [headers.join(',')];

  for (const d of devices) {
    const status = getFirmwareStatus(d);
    if (status === 'not-applicable') continue;
    const row = [
      d.id,
      `"${d.name.replace(/"/g, '""')}"`,
      d.category,
      d.firmwareVersion ?? '',
      d.firmwareLatest ?? '',
      firmwareStatusLabel(status),
      d.firmwareNotes ? `"${d.firmwareNotes.replace(/"/g, '""')}"` : '',
    ];
    lines.push(row.join(','));
  }

  return lines.join('\n');
}
