import type { CableRoute, PatchPanelPortDoc, PlacedDevice, ValidationIssue } from '../types/rack';

export interface PatchPanelDocSummary {
  totalPorts: number;
  documentedPorts: number;
  portsWithRoom: number;
  portsWithWireCode: number;
  portsTested: number;
}

export function getPatchPanelDocs(device: PlacedDevice): PatchPanelPortDoc[] {
  return device.patchPanelDocs ?? [];
}

export function findPatchPanelDoc(
  docs: PatchPanelPortDoc[],
  portIndex: number
): PatchPanelPortDoc | undefined {
  return docs.find((d) => d.portIndex === portIndex);
}

export function getPatchPanelDocSummary(
  device: PlacedDevice
): PatchPanelDocSummary {
  const docs = device.patchPanelDocs ?? [];
  const portCount = device.ports?.ethernet ?? 0;

  return {
    totalPorts: portCount,
    documentedPorts: docs.length,
    portsWithRoom: docs.filter((d) => d.destinationRoom?.trim()).length,
    portsWithWireCode: docs.filter((d) => d.wireCode).length,
    portsTested: docs.filter((d) => d.testedSpeed?.trim()).length,
  };
}

export function validatePatchPanelDocs(
  device: PlacedDevice,
  cables: CableRoute[]
): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  if (device.category !== 'patch-panel') return issues;

  const docs = device.patchPanelDocs ?? [];
  const portCount = device.ports?.ethernet ?? 0;

  // Check for ports that have a cable but no documentation
  for (let i = 0; i < portCount; i++) {
    const hasDoc = docs.some((d) => d.portIndex === i);
    const hasFrontCable = cables.some(
      (c) =>
        (c.fromDeviceId === device.id && c.fromPort?.type === 'ethernet' && c.fromPort.index === i) ||
        (c.toDeviceId === device.id && c.toPort?.type === 'ethernet' && c.toPort.index === i)
    );

    if (hasFrontCable && !hasDoc) {
      issues.push({
        id: `pp-doc-missing-${device.id}-${i}`,
        severity: 'info',
        title: 'Patch panel port lacks documentation',
        detail: `Port ${i + 1} on ${device.name} has a cable connected but no punch-down documentation.`,
        deviceIds: [device.id],
      });
    }
  }

  // Check for docs pointing to non-existent ports
  for (const doc of docs) {
    if (doc.portIndex >= portCount) {
      issues.push({
        id: `pp-doc-orphan-${device.id}-${doc.portIndex}`,
        severity: 'warning',
        title: 'Patch panel doc references invalid port',
        detail: `Documentation for port ${doc.portIndex + 1} on ${device.name} references a port that does not exist.`,
        deviceIds: [device.id],
      });
    }
  }

  return issues;
}

export function exportPatchPanelDocsMarkdown(device: PlacedDevice): string {
  const docs = device.patchPanelDocs ?? [];
  const portCount = device.ports?.ethernet ?? 0;

  const lines: string[] = [
    `# Patch Panel Documentation: ${device.name}`,
    '',
    `**Ports:** ${portCount} | **Documented:** ${docs.length}`,
    '',
    '| Port | Room | Wall Plate | Wire Code | Punch-Down Date | Tested Speed | Notes |',
    '|------|------|------------|-----------|-----------------|--------------|-------|',
  ];

  for (let i = 0; i < portCount; i++) {
    const doc = findPatchPanelDoc(docs, i);
    lines.push(
      `| ${i + 1} | ${doc?.destinationRoom ?? '-'} | ${doc?.wallPlate ?? '-'} | ${doc?.wireCode ?? '-'} | ${doc?.punchDownDate ?? '-'} | ${doc?.testedSpeed ?? '-'} | ${doc?.notes ?? '-'} |`
    );
  }

  lines.push('', '---', '', '*Generated by Homelab Rack Simulator*', '');
  return lines.join('\n');
}

export function exportPatchPanelDocsCsv(device: PlacedDevice): string {
  const docs = device.patchPanelDocs ?? [];
  const portCount = device.ports?.ethernet ?? 0;

  const headers = ['Port', 'Room', 'Wall Plate', 'Wire Code', 'Punch-Down Date', 'Tested Speed', 'Notes'];
  const lines: string[] = [headers.join(',')];

  for (let i = 0; i < portCount; i++) {
    const doc = findPatchPanelDoc(docs, i);
    const row = [
      String(i + 1),
      doc?.destinationRoom ? `"${doc.destinationRoom.replace(/"/g, '""')}"` : '',
      doc?.wallPlate ? `"${doc.wallPlate.replace(/"/g, '""')}"` : '',
      doc?.wireCode ?? '',
      doc?.punchDownDate ?? '',
      doc?.testedSpeed ? `"${doc.testedSpeed.replace(/"/g, '""')}"` : '',
      doc?.notes ? `"${doc.notes.replace(/"/g, '""')}"` : '',
    ];
    lines.push(row.join(','));
  }

  return lines.join('\n');
}
