import type { CableRoute, PlacedDevice, PortReservation, PortType, ValidationIssue } from '../types/rack';

export interface PortReservationSummary {
  totalCount: number;
  expiredCount: number;
  byDevice: Record<string, number>;
  byPortType: Record<string, number>;
}

export function getPortReservationsForDevice(
  reservations: PortReservation[],
  deviceId: string
): PortReservation[] {
  return reservations.filter((r) => r.deviceId === deviceId);
}

export function isPortReserved(
  reservations: PortReservation[],
  deviceId: string,
  portType: PortType,
  portIndex: number
): boolean {
  return reservations.some(
    (r) => r.deviceId === deviceId && r.portType === portType && r.portIndex === portIndex
  );
}

export function findReservation(
  reservations: PortReservation[],
  deviceId: string,
  portType: PortType,
  portIndex: number
): PortReservation | undefined {
  return reservations.find(
    (r) => r.deviceId === deviceId && r.portType === portType && r.portIndex === portIndex
  );
}

export function summarizePortReservations(
  reservations: PortReservation[]
): PortReservationSummary {
  const now = new Date().toISOString().slice(0, 10);
  const byDevice: Record<string, number> = {};
  const byPortType: Record<string, number> = {};
  let expiredCount = 0;

  for (const r of reservations) {
    byDevice[r.deviceId] = (byDevice[r.deviceId] ?? 0) + 1;
    byPortType[r.portType] = (byPortType[r.portType] ?? 0) + 1;
    if (r.expiryDate && r.expiryDate < now) {
      expiredCount += 1;
    }
  }

  return {
    totalCount: reservations.length,
    expiredCount,
    byDevice,
    byPortType,
  };
}

export function validatePortReservations(
  reservations: PortReservation[],
  devices: PlacedDevice[],
  cables: CableRoute[]
): ValidationIssue[] {
  const issues: ValidationIssue[] = [];

  for (const r of reservations) {
    const device = devices.find((d) => d.id === r.deviceId);
    if (!device) {
      issues.push({
        id: `port-res-missing-device-${r.id}`,
        severity: 'warning',
        title: 'Port reservation references missing device',
        detail: `Reservation "${r.purpose}" points to device ${r.deviceId} which no longer exists.`,
        deviceIds: [r.deviceId],
      });
      continue;
    }

    // Check if the port is already used by a cable
    const cableUsingPort = cables.find((c) => {
      const fromMatch =
        c.fromDeviceId === r.deviceId &&
        c.fromPort?.type === r.portType &&
        c.fromPort?.index === r.portIndex;
      const toMatch =
        c.toDeviceId === r.deviceId &&
        c.toPort?.type === r.portType &&
        c.toPort?.index === r.portIndex;
      return fromMatch || toMatch;
    });

    if (cableUsingPort) {
      issues.push({
        id: `port-res-cable-conflict-${r.id}`,
        severity: 'critical',
        title: 'Reserved port is already used by a cable',
        detail: `Port ${r.portType} ${r.portIndex} on ${device.name} is reserved for "${r.purpose}" but already connected to a cable.`,
        deviceIds: [r.deviceId],
        cableIds: [cableUsingPort.id],
      });
    }

    // Check expiry
    const now = new Date().toISOString().slice(0, 10);
    if (r.expiryDate && r.expiryDate < now) {
      issues.push({
        id: `port-res-expired-${r.id}`,
        severity: 'info',
        title: 'Port reservation has expired',
        detail: `Reservation "${r.purpose}" on ${device.name} expired on ${r.expiryDate}.`,
        deviceIds: [r.deviceId],
      });
    }
  }

  return issues;
}

export function exportPortReservationsMarkdown(
  reservations: PortReservation[],
  devices: PlacedDevice[]
): string {
  const deviceName = (id: string) => devices.find((d) => d.id === id)?.name ?? id;

  const lines: string[] = [
    '# Port Reservations',
    '',
    `**Total Reservations:** ${reservations.length}`,
    '',
    '| Device | Port | Purpose | Expected Device | Owner | Expiry | Notes |',
    '|--------|------|---------|-----------------|-------|--------|-------|',
  ];

  for (const r of reservations) {
    lines.push(
      `| ${deviceName(r.deviceId)} | ${r.portType} ${r.portIndex + 1} | ${r.purpose} | ${r.expectedDevice ?? '-'} | ${r.owner ?? '-'} | ${r.expiryDate ?? '-'} | ${r.notes ?? '-'} |`
    );
  }

  lines.push('', '---', '', '*Generated by Homelab Rack Simulator*', '');
  return lines.join('\n');
}

export function exportPortReservationsCsv(
  reservations: PortReservation[],
  devices: PlacedDevice[]
): string {
  const deviceName = (id: string) => devices.find((d) => d.id === id)?.name ?? id;

  const headers = ['ID', 'Device', 'Port Type', 'Port Index', 'Purpose', 'Expected Device', 'Owner', 'Expiry', 'Notes'];
  const lines: string[] = [headers.join(',')];

  for (const r of reservations) {
    const row = [
      r.id,
      `"${deviceName(r.deviceId).replace(/"/g, '""')}"`,
      r.portType,
      String(r.portIndex + 1),
      `"${r.purpose.replace(/"/g, '""')}"`,
      r.expectedDevice ? `"${r.expectedDevice.replace(/"/g, '""')}"` : '',
      r.owner ? `"${r.owner.replace(/"/g, '""')}"` : '',
      r.expiryDate ?? '',
      r.notes ? `"${r.notes.replace(/"/g, '""')}"` : '',
    ];
    lines.push(row.join(','));
  }

  return lines.join('\n');
}
