import type { RackPhoto } from '../types/rack';

export function summarizePhotos(photos: RackPhoto[]) {
  return {
    total: photos.length,
    withDate: photos.filter((p) => p.capturedAt).length,
    withNotes: photos.filter((p) => p.notes).length,
  };
}

export function exportPhotosMarkdown(photos: RackPhoto[]): string {
  const lines: string[] = [
    '# Rack Photo Log',
    '',
    `**Total Photos:** ${photos.length}`,
    '',
  ];

  for (const p of photos) {
    lines.push(`## ${p.label}`, '');
    if (p.capturedAt) lines.push(`**Captured:** ${p.capturedAt}`);
    lines.push(`**Source:** ${p.source}`);
    if (p.notes) lines.push(`**Notes:** ${p.notes}`);
    lines.push('');
  }

  lines.push('---', '', '*Generated by Homelab Rack Simulator*', '');
  return lines.join('\n');
}
