import type { RoomRack } from '../types/rack';

const RACK_WIDTH_19IN_MM = 482.6;
const RACK_WIDTH_10IN_MM = 254;
const RACK_DEPTH_STANDARD_MM = 600;
const RACK_DEPTH_DEEP_MM = 1000;
const U_TO_MM = 44.45;
const BASE_HEIGHT_MM = 100;

export function getRackDimensions(rackType: RoomRack['rackType'], heightU: number) {
  const widthMm = rackType === '10in' ? RACK_WIDTH_10IN_MM : RACK_WIDTH_19IN_MM;
  const depthMm = rackType === '10in' ? RACK_DEPTH_STANDARD_MM : RACK_DEPTH_DEEP_MM;
  const heightMm = BASE_HEIGHT_MM + heightU * U_TO_MM;
  return { widthMm, depthMm, heightMm };
}

export function summarizeRoomRacks(racks: RoomRack[]) {
  const byType = new Map<string, number>();
  let totalHeightU = 0;
  for (const r of racks) {
    byType.set(r.rackType, (byType.get(r.rackType) ?? 0) + 1);
    totalHeightU += r.heightU;
  }
  return {
    total: racks.length,
    byType: Object.fromEntries(byType),
    totalHeightU,
  };
}

export interface RoomRackOverlap {
  rackAId: string;
  rackBId: string;
  rackAName: string;
  rackBName: string;
}

export function findRackOverlaps(racks: RoomRack[]): RoomRackOverlap[] {
  const overlaps: RoomRackOverlap[] = [];
  for (let i = 0; i < racks.length; i++) {
    const a = racks[i];
    const aDim = getRackDimensions(a.rackType, a.heightU);
    for (let j = i + 1; j < racks.length; j++) {
      const b = racks[j];
      const bDim = getRackDimensions(b.rackType, b.heightU);
      const aLeft = a.xMm;
      const aRight = a.xMm + aDim.widthMm;
      const aTop = a.yMm;
      const aBottom = a.yMm + aDim.depthMm;
      const bLeft = b.xMm;
      const bRight = b.xMm + bDim.widthMm;
      const bTop = b.yMm;
      const bBottom = b.yMm + bDim.depthMm;
      if (aLeft < bRight && aRight > bLeft && aTop < bBottom && aBottom > bTop) {
        overlaps.push({
          rackAId: a.id,
          rackBId: b.id,
          rackAName: a.name,
          rackBName: b.name,
        });
      }
    }
  }
  return overlaps;
}

export function getRoomBounds(racks: RoomRack[]) {
  if (racks.length === 0) return { minX: 0, minY: 0, maxX: 0, maxY: 0, widthMm: 0, depthMm: 0 };
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const r of racks) {
    const dim = getRackDimensions(r.rackType, r.heightU);
    minX = Math.min(minX, r.xMm);
    minY = Math.min(minY, r.yMm);
    maxX = Math.max(maxX, r.xMm + dim.widthMm);
    maxY = Math.max(maxY, r.yMm + dim.depthMm);
  }
  return {
    minX,
    minY,
    maxX,
    maxY,
    widthMm: maxX - minX,
    depthMm: maxY - minY,
  };
}

export function exportRoomRacksMarkdown(racks: RoomRack[]): string {
  const summary = summarizeRoomRacks(racks);
  const bounds = getRoomBounds(racks);
  const lines: string[] = [
    '# Room Rack Layout',
    '',
    `**Total Racks:** ${summary.total}`,
    `**Total Height:** ${summary.totalHeightU}U`,
    `**Room Footprint:** ${(bounds.widthMm / 1000).toFixed(2)}m × ${(bounds.depthMm / 1000).toFixed(2)}m`,
    '',
  ];

  for (const r of racks) {
    const dim = getRackDimensions(r.rackType, r.heightU);
    lines.push(`## ${r.name}`, '');
    lines.push(`**Type:** ${r.rackType} · **Height:** ${r.heightU}U`);
    lines.push(`**Position:** (${r.xMm}mm, ${r.yMm}mm)`);
    lines.push(`**Dimensions:** ${dim.widthMm}mm × ${dim.depthMm}mm × ${Math.round(dim.heightMm)}mm`);
    if (r.notes) lines.push(`**Notes:** ${r.notes}`);
    lines.push('');
  }

  const overlaps = findRackOverlaps(racks);
  if (overlaps.length > 0) {
    lines.push('## Overlap Warnings', '');
    for (const o of overlaps) {
      lines.push(`- **${o.rackAName}** overlaps **${o.rackBName}**`);
    }
    lines.push('');
  }

  lines.push('---', '', '*Generated by Homelab Rack Simulator*', '');
  return lines.join('\n');
}
