import type { DeviceTemplate } from '../types/rack';

export type TemplateField =
  | 'rackMountable'
  | 'customWidthMm'
  | 'ports'
  | 'portFaceOverrides'
  | 'portLayouts'
  | 'mountType'
  | 'mountSide0U'
  | 'outletFacing';

export const TRACKED_FIELDS: { key: TemplateField; label: string }[] = [
  { key: 'rackMountable', label: 'Rack mountable flag' },
  { key: 'customWidthMm', label: 'Custom width mm' },
  { key: 'ports', label: 'Port layout' },
  { key: 'portFaceOverrides', label: 'Port face overrides' },
  { key: 'portLayouts', label: 'Detailed port layouts' },
  { key: 'mountType', label: '0U mount type' },
  { key: 'mountSide0U', label: '0U mount side' },
  { key: 'outletFacing', label: 'Outlet facing' },
];

export interface FieldCoverage {
  field: TemplateField;
  label: string;
  present: number;
  total: number;
  percent: number;
}

export interface CategoryCoverage {
  category: string;
  count: number;
  avgCoveragePercent: number;
}

export interface TemplateQualityResult {
  totalTemplates: number;
  fieldCoverage: FieldCoverage[];
  categoryCoverage: CategoryCoverage[];
  lowQualityTemplates: { template: DeviceTemplate; missingFields: TemplateField[] }[];
  overallScore: number; // 0-100
}

export function analyzeTemplateQuality(catalog: DeviceTemplate[]): TemplateQualityResult {
  const total = catalog.length;
  const fieldCoverage: FieldCoverage[] = TRACKED_FIELDS.map(({ key, label }) => {
    const present = catalog.filter((t) => t[key] !== undefined).length;
    return {
      field: key,
      label,
      present,
      total,
      percent: total > 0 ? Math.round((present / total) * 100) : 0,
    };
  });

  const categories = new Map<string, DeviceTemplate[]>();
  for (const t of catalog) {
    const list = categories.get(t.category) ?? [];
    list.push(t);
    categories.set(t.category, list);
  }

  const categoryCoverage: CategoryCoverage[] = Array.from(categories.entries())
    .map(([category, items]) => {
      const coveragePercents = items.map((t) => {
        const present = TRACKED_FIELDS.filter(({ key }) => t[key] !== undefined).length;
        return (present / TRACKED_FIELDS.length) * 100;
      });
      const avg = coveragePercents.reduce((a, b) => a + b, 0) / coveragePercents.length;
      return { category, count: items.length, avgCoveragePercent: Math.round(avg) };
    })
    .sort((a, b) => b.avgCoveragePercent - a.avgCoveragePercent);

  const lowQualityThreshold = 25; // percent
  const lowQualityTemplates = catalog
    .map((t) => {
      const missingFields = TRACKED_FIELDS.filter(({ key }) => t[key] === undefined).map(({ key }) => key);
      const coverage = ((TRACKED_FIELDS.length - missingFields.length) / TRACKED_FIELDS.length) * 100;
      return { template: t, missingFields, coverage };
    })
    .filter((item) => item.coverage < lowQualityThreshold)
    .map((item) => ({ template: item.template, missingFields: item.missingFields }));

  const overallScore = total > 0
    ? Math.round(fieldCoverage.reduce((sum, f) => sum + f.percent, 0) / fieldCoverage.length)
    : 0;

  return {
    totalTemplates: total,
    fieldCoverage,
    categoryCoverage,
    lowQualityTemplates,
    overallScore,
  };
}

export function exportTemplateQualityMarkdown(result: TemplateQualityResult): string {
  const lines: string[] = [
    '# Device Catalog Data Quality Report',
    '',
    `**Overall Score:** ${result.overallScore}%`,
    `**Total Templates:** ${result.totalTemplates}`,
    `**Low Quality Templates:** ${result.lowQualityTemplates.length}`,
    '',
    '## Field Coverage',
    '',
    '| Field | Present | Coverage |',
    '|-------|---------|----------|',
  ];

  for (const f of result.fieldCoverage) {
    lines.push(`| ${f.label} | ${f.present}/${f.total} | ${f.percent}% |`);
  }

  lines.push('', '## Coverage by Category', '');
  for (const c of result.categoryCoverage) {
    lines.push(`- **${c.category}**: ${c.count} templates, ${c.avgCoveragePercent}% avg coverage`);
  }

  if (result.lowQualityTemplates.length > 0) {
    lines.push('', '## Low Quality Templates', '');
    for (const item of result.lowQualityTemplates) {
      lines.push(`- **${item.template.name}** (${item.template.category}): missing ${item.missingFields.join(', ')}`);
    }
  }

  lines.push('', '---', '', '*Generated by Homelab Rack Simulator*', '');
  return lines.join('\n');
}
